# syntax version.
version: "3.7"

services:
  # nginx:
  #   container_name: nginx
  #   image: nginx:1.16.1
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/sites:/etc/nginx/conf.d
  #   restart: always
  #   depends_on:
  #     - sports-admin
  #   networks:
  #     - backend

  mysql:
    container_name: go-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: abcd1234
      MYSQL_DATABASE: demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: abcd1234
    networks: 
      - backend
    volumes:
      - ./storage/mysql:/var/lib/mysql

  redis:
    container_name: go-redis
    image: redis:5.0.9-buster
    ports:
      - "6379:6379"
    stdin_open: true
    tty: true
    volumes:
      - ./storage/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend

  # fluentd:
  #   build: 
  #     context: ./fluentd
  #   container_name: go-fluentd
  #   volumes:
  #     - ./fluentd/conf:/fluentd/etc
  #     - ./fluentd:/fluentd/log
  #   ports:
  #     - "24224:24224"
  #     - "24224:24224/udp"
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge
