# syntax version.
version: "3.7"

services:
  # nginx:
  #   container_name: nginx
  #   image: nginx:1.16.1
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/sites:/etc/nginx/conf.d
  #   restart: always
  #   depends_on:
  #     - sports-admin
  #   networks:
  #     - backend

  mysql:
    container_name: go-mysql
    image: mysql:5.7
    ports:
      - ${MYSQL_EXPOSE_PORT}:3306
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: admin
      MYSQL_PASSWORD: abcd1234
    networks: 
      - backend
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql

  redis:
    container_name: go-redis
    image: redis:5.0.9-buster
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    stdin_open: true
    tty: true
    networks: 
      - backend

  # fluentd:
  #   build: 
  #     context: ./fluentd
  #   container_name: go-fluentd
  #   volumes:
  #     - ./fluentd/conf:/fluentd/etc
  #     - ./fluentd:/fluentd/log
  #   ports:
  #     - "24224:24224"
  #     - "24224:24224/udp"
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge
