scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: workspace
    scrape_interval: 10s
    static_configs:
      - targets:
        - workspace:8082